version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn -f my-app/pom.xml test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -f my-app/pom.xml package
artifacts:
  files:
    - target/m*
    - appspec.yml
  discard-paths: yes
