
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: |
        mvn -B package --file ./my-app/pom.xml
        mvn validate --file ./my-app/pom.xml -DbumpPatch
        mvn clean
    
    - name: update file and push to remote
      run: |
          cd my-app
          tree
          git config --global user.name "vica.lish"
          git config --global user.email "vicalish@gmail.com"
          git add pom.xml
          git commit -m "Update pom.xml"
          git push
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: 'vicalish'
        password: ${{ secrets.DOCKER_HUB_USERNAME }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: vicalish/github-proj:latest
